last_updated = "2026-02-27"
execution_time_secs = 2.15

[imgt.IGH]
total_sequences = 2452
perfect_sequences = 2449
perfect_pct = 99.88
overall_accuracy = 100.0

[imgt.IGK]
total_sequences = 1485
perfect_sequences = 1481
perfect_pct = 99.73
overall_accuracy = 99.99

[imgt.IGL]
total_sequences = 371
perfect_sequences = 369
perfect_pct = 99.46
overall_accuracy = 99.99

[imgt.TRA]
total_sequences = 865
perfect_sequences = 763
perfect_pct = 88.21
overall_accuracy = 99.49

[imgt.TRB]
total_sequences = 934
perfect_sequences = 911
perfect_pct = 97.54
overall_accuracy = 99.79

[imgt.TRD]
total_sequences = 23
perfect_sequences = 23
perfect_pct = 100.0
overall_accuracy = 100.0

[imgt.TRG]
total_sequences = 25
perfect_sequences = 24
perfect_pct = 96.0
overall_accuracy = 99.96

[kabat.IGH]
total_sequences = 2452
perfect_sequences = 2449
perfect_pct = 99.88
overall_accuracy = 100.0

[kabat.IGK]
total_sequences = 1485
perfect_sequences = 1480
perfect_pct = 99.66
overall_accuracy = 99.99

[kabat.IGL]
total_sequences = 371
perfect_sequences = 369
perfect_pct = 99.46
overall_accuracy = 99.99
