// We need to forward routine registration from C to Rust to avoid the linker
// removing the static library if it does not see any object referenced from C.
//
// This file is autogenerated by `rextendr::use_extendr()` and should not be
// edited by hand.

void R_init_immunum_extendr(void *dll);

void R_init_immunum(void *dll) {
    R_init_immunum_extendr(dll);
}
