# Generated by extendr: do not edit by hand
#
# Hand-written to match symbols from src/extendr/src/lib.rs.
# Other wrap__* symbols are called directly via .Call() from R/immunum.R.

#' Return the version of the underlying `immunum` Rust crate
#'
#' This is the version of the Rust core, not the R package wrapper.
#' Returned as a `character(1)` to mirror Python's
#' `immunum._internal.__version__`.
#'
#' @return A length-1 character vector with the crate version.
#' @export
#' @examples
#' immunum_version()
immunum_version <- function() .Call(wrap__immunum_version)

# ── Internal batch wrappers (not exported) ────────────────────────────────────
# Accessible via immunum:::numbering_batch() etc.
# Chains and scheme are normalised before the Rust call so these functions
# accept the same aliases as Annotator$new().

numbering_batch <- function(seqs, chains, scheme, min_confidence = NULL) {
  chains <- normalize_chains(chains)
  scheme <- normalize_scheme(scheme)
  .Call(wrap__numbering_batch, seqs, chains, scheme, min_confidence)
}

segmentation_batch <- function(seqs, chains, scheme, min_confidence = NULL) {
  chains <- normalize_chains(chains)
  scheme <- normalize_scheme(scheme)
  .Call(wrap__segmentation_batch, seqs, chains, scheme, min_confidence)
}

numbering_batch_with <- function(seqs, annotator) {
  if (!inherits(annotator, "Annotator")) {
    stop("`annotator` must be an Annotator R6 instance", call. = FALSE)
  }
  .Call(wrap__numbering_batch_with, seqs,
        annotator$.__enclos_env__$private$.inner)
}

segmentation_batch_with <- function(seqs, annotator) {
  if (!inherits(annotator, "Annotator")) {
    stop("`annotator` must be an Annotator R6 instance", call. = FALSE)
  }
  .Call(wrap__segmentation_batch_with, seqs,
        annotator$.__enclos_env__$private$.inner)
}
