# Generated by extendr: do not edit by hand
#
# Hand-written to match symbols from src/extendr/src/lib.rs.
# Other wrap__* symbols are called directly via .Call() from
# R/immunum.R and R/polars.R.

#' Return the version of the underlying `immunum` Rust crate
#'
#' @return A length-1 character vector with the crate version.
#' @export
#' @examples
#' immunum_version()
immunum_version <- function() .Call(wrap__immunum_version)
