pub mod annotator;
pub mod consensus_scoring;
pub mod constants;
pub mod fastx;
pub mod gap_penalty;
pub mod insertion_numbering;
pub mod needleman_wunsch;
pub mod numbering_scheme_type;
pub mod prefiltering;
pub mod result;
pub mod schemes;
pub mod scoring_matrix;
pub mod types;
// Binding modules
#[cfg(feature = "python")]
pub mod python_bindings;
#[cfg(feature = "wasm")]
pub mod wasm_bindings;
