name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Format Check
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test
      - name: Benchmark validation
        run: cargo test --release --test abpdseq_validation_test test_abpdseq_validation_full -- --ignored --nocapture
      - name: Build
        run: cargo build
